=== brum0047/4662XML1/tableattr.dtd
<!ELEMENT crimereport (incident)>
<!ELEMENT incident (date, time, address, type)
<!ELEMENT date (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT crimetype (#PCDATA)>

<!ATTLIST crimetype type (ROBPER|THEFT|BIKE|ARSON|ASSAULT|FRAUD|CSC|MISPER)>

=== brum0047/4662XML1/table.xml
<?xml version="1.0" encoding= "UTF-8"?>
<!DOCTYPE table SYSTEM "tableattr.dtd">

<crimereport>
	<incident>
		<time>19:35</time>
		<date>11/10/2018</date>
		<address>510 Washington Ave SE</address>
		<crimetype>ROBPER</crimetype>
	</incident>
	<incident>
		<time>18:49</time>
		<date>11/12/2018</date>
		<address>2221 University AVE SE</address>
		<crimetype>ARSON</crimetype>
	</incident>
	<incident>
		<time>09:56</time>
		<date>11/13/2018</date>
		<address>433 CHURCH ST SE</address>
		<crimetype>BIKE</crimetype>
	</incident>
	<incident>
		<time>11:37</time>
		<date>11/15/2018</date>
		<address>1520 University AVE SE</address>
		<crimetype>THEFT</crimetype>
	</incident>
</crimereport>
